### ISSUE TITLE
[BUG] Spam jumping while on a bicycle

### ISSUE THREAD

**Issue by Unsxxn** [ParadymHub/bugs#10]
**Describe the bug**
When riding a bike you can spam jump and get up to ridiculous speeds by spamming the space bar and holding shift

**To Reproduce**
1. Find a bike
2. hold shift while moving forward
3. spam your jump key on the bike

**Expected behavior**
There should be a interval between jumping so you cant spam it to get to 70+ mph

**Comment by tclrd** [comment]
Added a 2300ms cooldown on jumping across all bike models
