### ISSUE TITLE
Respawning when down causes instant death again

### ISSUE THREAD

**Issue by MissCrazyKay** [ParadymHub/bugs#12]
**Describe the bug**
When down and prompted to respawn, you respawn at the hospital and fall through the floor. This makes you fall to your death again in the tunnels. Just a continuous cycle

**To Reproduce**
1. Get downed
2. Press "e" for respawn
3. Puts you at hospital where you fall through floor into the tunnels and die again.
4. Press "e" again to respawn.
5. Behavior begins to repeat itself.

**Expected behavior**
Wake up at hospital with health... not falling through the floor and dying. 

**Screenshots**
n/a

**Additional context**
n/a

**Comment by tclrd** [comment]
Adjusted coordinates of respawn location and reworked respawning logic.
