### ISSUE TITLE
[BUG] Player stuck in trunk state when car deletes

### ISSUE THREAD

**Issue by Forsakenzzzz** [ParadymHub/bugs#14]
**Describe the bug**
The player is still considered trunk when the car is deleted or store at a garage. Player is left invisible and invincible. 

**To Reproduce**
1. Place a player in a trunk
2. Store the car in a garage 

**Expected behavior**
Player should get automatically untrunked upon car deletion.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by tclrd** [comment]
Player is now appropriately removed from trunk when vehicle no longer exists / is out of range in the event they are separated to prevent scuff.
