### ISSUE TITLE
[BUG] Custom Audio Left Ear

### ISSUE THREAD

**Issue by Forsakenzzzz** [ParadymHub/bugs#4]
**Describe the bug**
The custom gun sound audio is only playing in the left ear while the right ear is still playing default gun sounds

**To Reproduce**
1. Shoot gun
2. Listen

**Expected behavior**
Custom audio playing in both ears.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by tclrd** [comment]
Custom audio has been removed until a better solution can be implemented
