### ISSUE TITLE
[BUG] Third Person Shooting from Bikes

### ISSUE THREAD

**Issue by Forsakenzzzz** [ParadymHub/bugs#5]
**Describe the bug**
When aiming and firing guns from bikes, you are still able to shoot from third person.

**To Reproduce**
1. Get on Bike
2. aim gun
3. un-aim gun then toggle view perspective
4. aim gun again

**Expected behavior**
shooting from any vehicle should force first person.

**Screenshots**
https://i.imgur.com/hqrKyyS.jpeg

**Additional context**
N/A

**Comment by tclrd** [comment]
![image](https://github.com/ParadymHub/bugs/assets/24597620/9f88b145-70fa-4dae-9dab-2912ef3d0f60)
![image](https://github.com/ParadymHub/bugs/assets/24597620/20fff340-c783-4cd5-890f-2486b8cb5c98)

Updated camera checking to consider vehicle type, should resolve for all instances on any vehicle now 🤠👍
