### ISSUE TITLE
[BUG] Aiming/shooting while 'hands up'

### ISSUE THREAD

**Issue by Unsxxn** [ParadymHub/bugs#9]
**Describe the bug**
While hands up/ragdoll/pointing you can still aim your weapon and shoot it

**To Reproduce**
 handsup/ragdoll/point and then aim and shoot while holding the specific keybind

**Expected behavior**
When I went to aim while handsup/pointing/ragdoll I expect it to ignore my request to aim or shoot

**Screenshots**
![image](https://github.com/ParadymHub/bugs/assets/118211931/69a49cf9-de4d-42a5-9439-dc4fc21492f2)
![image](https://github.com/ParadymHub/bugs/assets/118211931/303060fd-0cec-4998-80db-aad3a0a03c7c)

**Comment by tclrd** [comment]
Players are no longer able to aim/shoot while emoting. Shooting while rag dolled still possible.
